# Generated by Django 4.2.4 on 2023-08-10 14:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0003_room_host'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['-updated', '-created']},
        ),
        migrations.AddField(
            model_name='room',
            name='particapants',
            field=models.ManyToManyField(blank=True, related_name='particapants', to=settings.AUTH_USER_MODEL),
        ),
    ]
